app = 'telegram-video-bot-7wip4g'
primary_region = 'arn'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  BOT_TOKEN = ''

[processes]
  worker = 'python bot.py'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
